[package]
name = "alexyt"
version = "0.1.0"
authors = ["Alether <gotenwinz99@gmail.com>"]

[dependencies]
cgmath = "0.14.1"
gl = "0.6.2"
glfw = "0.15.0"
image = "0.14.0"
time = "0.1"
rand = "0.3"
rodio = "0.5.2"
rusttype = "0.3.0"
unicode-normalization = "0.1.0"