[package]
name = "ale_app"
version = "0.1.0"
authors = ["Andreas Terrius <andreas.terrius@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ale_glfw = { path = "../ale_glfw" }
ale_opengl = { path = "../ale_opengl" }
ale_math = { path = "../ale_math" }
ale_input = { path = "../ale_input" }
ale_resource = { path = "../ale_resource" }
ale_ecs = { path = "../ale_ecs" }

ale_camera = { path = "../ale_camera" }
ale_mesh = { path = "../ale_mesh" }
ale_shader = { path = "../ale_shader"}
ale_material = { path = "../ale_material" }