[package]
name = "ale_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ale_input = { path = "../ale_input" }
hecs = "0.7.6"
traitcast = "0.5.0"
traitcast_core = "0.2.0"
inventory = "0.1.*"