name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Update
      run: sudo apt-get update
    - name: Setup
      run: sudo apt-get install libasound2-dev libglfw3-dev xorg-dev
    - name: Build
      run: cargo build --verbose
